### ISSUE TITLE
It won't compile under linux

### ISSUE THREAD

**Issue by Mihot7** [Auror-OS/AurorOS#3]
**Describe the bug**
It doesn't compile

**To Reproduce**
1. Clone repo using git
2. use make command

**Expected behavior**
The OS has built

**Screenshots**
![obraz](https://github.com/Interpuce/AurorOS/assets/105102302/c7bd61ab-05d1-43a6-a022-bcd8d7887b64)

**Additional context**
Log:
gcc -ffreestanding -nostdlib out/obj/drivers/keyboard/ps2.c.o out/obj/drivers/fs/fat32/fat32.c.o out/obj/drivers/console/init.c.o out/obj/drivers/vga/detect.c.o out/obj/drivers/vga/console.c.o out/obj/kernel/main.c.o  -o kernelImg
/usr/bin/ld: i386 architecture of input file `out/obj/drivers/keyboard/ps2.c.o' is incompatible with i386:x86-64 output
/usr/bin/ld: i386 architecture of input file `out/obj/drivers/fs/fat32/fat32.c.o' is incompatible with i386:x86-64 output
/usr/bin/ld: i386 architecture of input file `out/obj/drivers/console/init.c.o' is incompatible with i386:x86-64 output
/usr/bin/ld: i386 architecture of input file `out/obj/drivers/vga/detect.c.o' is incompatible with i386:x86-64 output
/usr/bin/ld: i386 architecture of input file `out/obj/drivers/vga/console.c.o' is incompatible with i386:x86-64 output
/usr/bin/ld: i386 architecture of input file `out/obj/kernel/main.c.o' is incompatible with i386:x86-64 output
/usr/bin/ld: warning: cannot find entry symbol _start; defaulting to 0000000000001000
/usr/bin/ld: out/obj/kernel/main.c.o: in function `main':
main.c:(.text.startup+0xb): undefined reference to `_GLOBAL_OFFSET_TABLE_'
/usr/bin/ld: out/obj/drivers/console/init.c.o: in function `cm_init':
init.c:(.text+0x8): undefined reference to `_GLOBAL_OFFSET_TABLE_'
/usr/bin/ld: out/obj/drivers/console/init.c.o: in function `cm_write_string':
init.c:(.text+0x38): undefined reference to `_GLOBAL_OFFSET_TABLE_'
/usr/bin/ld: out/obj/drivers/vga/console.c.o: in function `vga_set_cursor_position':
console.c:(.text+0x16): undefined reference to `_GLOBAL_OFFSET_TABLE_'
/usr/bin/ld: out/obj/drivers/vga/console.c.o: in function `set_char_attribute':
console.c:(.text+0x76): undefined reference to `_GLOBAL_OFFSET_TABLE_'
/usr/bin/ld: out/obj/drivers/vga/console.c.o:console.c:(.text+0x97): more undefined references to `_GLOBAL_OFFSET_TABLE_' follow
/usr/bin/ld: out/obj/drivers/keyboard/ps2.c.o: file class ELFCLASS32 incompatible with ELFCLASS64
/usr/bin/ld: final link failed: file in wrong format
collect2: error: ld returned 1 exit status
make: *** [Makefile:36: kernelImg] Błąd 1

**Comment by gorciu-official** [comment]
# I know!
The Makefile was rewrited to build AurorOS correctly, but in reality the OS cannot build now. I am going to fix this and these errors in the future, but now... kernel is useless and compiling it makes no sense. 

About `undefined reference to GLOBAL_OFFSET_TABLE`: this will be defined in the next commint when I back to home
